#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 16 08:39:41 2019

@author: irenetricarico
"""
import numpy as np

import scipy.cluster.hierarchy  as shc

from scipy.cluster.hierarchy import linkage,dendrogram
import matplotlib.pyplot as plt
import csv
import pandas as pd

#data_vf=pd.read_csv('data_train.csv')
#data_vf.set_index('Store_ID', inplace=True)

#data_vf

# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv (see later) 
data = pd.read_csv("data_train.csv") 
# Preview the first 5 lines of the loaded data 
#data.head()


# the following script to filter the first three columns from our dataset:


plt.figure(figsize=(10,7))
plt.title('dendrogram')
dend = shc.dendrogram(shc.linkage(data,method='ward'))


from sklearn.cluster import AgglomerativeClustering

cluster = AgglomerativeClustering(n_clusters=3, affinity='euclidean', linkage='ward')  
cluster.fit_predict(data) 

#  You can see the cluster labels from all of your data points. Since we had five clusters, we have five labels in the output i.e. 0 to 4.
plt.figure(figsize=(10, 7))  


plt.scatter(data.iloc[:,0], data.iloc[:,1], c=cluster.labels_, cmap='rainbow')  
